// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjwkuxebjuvyxfeogwbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqd2t1eGVianV2eXhmZW9nd2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTEwOTcsImV4cCI6MjA2MzcyNzA5N30.WuRWMVCTQ9StPsWBg68ZrgVzOLx-3UD0JXWAIT_hMuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);